### ISSUE TITLE
Used paragraph numbers in filesystem.hpp refer to the C++17 standard

### ISSUE THREAD

**Issue by albert-github** [gulrak/filesystem#113]
Might be a bit off topic.

In the current filsystem.hpp source code we see e.g.:
```
// 30.10.8 class path
class GHC_FS_API_CLASS path
```
Here the 30.10.8 is referring to the C++17 standard paragraph, though in:
- C++20 standard the paragraph is 29.11.7
- C++23 draft standard the paragraph is 29.11.6

Maybe a solution would be:
- to refer, in this case, to [fs.class.path]
- or mention at least that the numbers are derived from the C++17 standard

similar for the other mentioned paragraph numbers.

**Comment by gulrak** [comment]
Yeah, a valid point, I'm unhappy with the now misleading paragraph numbers myself, even if I kept them in regard to the first sentence of the readme: _"tightly following the C++17 standard with very few documented exceptions"_, but I understand that this is nothing more than a hint, and after adding C++20 support it gets kinda diffuse.

I think that switching to the identifier-like names e.g. `[fs.class.path]` might be the best way, and the test cases already use them as Catch2 tags to be able to select tests. Still I wouldn't schedule a release just with this, so a release will depend on other issues making a release necessary.

**Comment by albert-github** [comment]
- I think indeed good idea to reference to the `[...]` tags
- it is definitely not worth a new release as it is just a minor problem for people reading the code (and most of the time these people will know about where to find the C++17 standard).

**Comment by gulrak** [comment]
This is now part of release [v1.5.6](https://github.com/gulrak/filesystem/releases/tag/v1.5.6)
