### ISSUE TITLE
path is not implicitly constructible from UTF-8, UTF-16 or UTF-32 literals

### ISSUE THREAD

**Issue by zero9178** [gulrak/filesystem#119]
Implementations of std::filesystem I have tested (libc++, libstdc++ and MSVC STL) all support the use of u8, u16 and u32 string literals to construct a path using constructor 5 described here in cppreference: https://en.cppreference.com/w/cpp/filesystem/path/path

The relevant standard text is https://eel.is/c++draft/fs.path.type.cvt I believe, though I am not well versed in the C++ Standard.

I encountered this issue with the following code:
```cpp
#include <filesystem>

int main()
{
    ghc::filesystem::exists(u8"test");
}
```
which failed to compile in C++20 mode when I was using either Clang 12 or GCC 11 (on Windows). I believe it should also be reproducible using UTF-16 or UTF-32 literals in C++17 mode.

The same code in CE, showing all 3 STL implementations compiling the above:
https://godbolt.org/z/Gd835xxGv

**Comment by gulrak** [comment]
Indeed, that should work while compiling with C++20 mode, and I can reproduce the issue.
Thanks for reporting, I'll look into it.

**Comment by gulrak** [comment]
With the fix from branch [feature-119-support-u8-u16-u32-literals](https://github.com/gulrak/filesystem/tree/feature-119-support-u8-u16-u32-literals) it works for me now. (But I don't have Clang 12 or GCC 11 on Windows at hand, tested on macOS with Clang and Windows with VS2019.

**Comment by zero9178** [comment]
Just checked out the branch and ran your whole testsuite against both toolchains and can happily confirm that it's working and that there are no regressions either.
