### ISSUE TITLE
Recursive directory iterator tries to follow symlink on macOS

### ISSUE THREAD

**Issue by wolfv** [gulrak/filesystem#122]
**Describe the bug**
I am recursing over a directory with symlinks inside. These symlinks have no valid target though. Unfortunately when running over this with a recursive directory iterator, it throws with "No such file or directory" when _incrementing_ the iterator.

```
drwxr-xr-x  4 wolfvollprecht  staff  128 May 12 17:14 .
drwxr-xr-x  5 wolfvollprecht  staff  160 May 12 17:14 ..
lrwxrwxr-x  1 wolfvollprecht  staff   29 Feb 21 15:30 libcrypto.1.1.dylib -> ../../lib/libcrypto.1.1.dylib
lrwxrwxr-x  1 wolfvollprecht  staff   26 Feb 21 15:30 libssl.1.1.dylib -> ../../lib/libssl.1.1.dylib
```

**To Reproduce**
Downloading, unpacking and iterating over the contents of this file https://anaconda.org/conda-forge/mysql-libs/8.0.23/download/osx-64/mysql-libs-8.0.23-hbeb7981_1.tar.bz2 should lead to the same issue. It contains the missing symlinks mentioned above. I observed this on macOS only so far.

The STL implementation does not have this problem.

This came up in mamba: https://github.com/mamba-org/mamba/issues/950

**Expected behavior**
I'd like the iterator to move to the next item.

**Comment by gulrak** [comment]
Thanks for reporting, I'll look into it.

**Comment by gulrak** [comment]
This is now part of release [v1.5.6](https://github.com/gulrak/filesystem/releases/tag/v1.5.6)

**Comment by wolfv** [comment]
Thanks!
