### ISSUE TITLE
Please port this library for Android Open Source Project (AOSP)

### ISSUE THREAD

**Issue by uskovboris** [gulrak/filesystem#127]
There is a luck of the std::filesystem in Android

**Comment by uskovboris** [comment]
Please implement Android.mk for the library to build it for embedded devices

**Comment by gulrak** [comment]
I would like to, but I currently don't have any Android development setup, as I don't use Android in any way. I know of people using it on with NDK versions that not support std::filesystem (as far as I know before NDK r22). But I guess most of them just copy the `filesystem.hpp` to their Projects and include it where needed, as it is header-only, so no real library is build.

If someone wants to help with an `Android.mk` that would help AOSP usage, I'd be glad to get a PR, but without setting up an Android environment and using it, I sadly don't see how I can do this.

**Comment by gulrak** [comment]
Closing this, as nobody stepped in and I'm not able to support this feature myself, as I can't invest the time, not doing any Android work myself. PRs still welcome.
