### ISSUE TITLE
on windows if -D_UNICODE or -DUNICODE is defined, should not use wchar storage

### ISSUE THREAD

**Issue by thefallentree** [gulrak/filesystem#131]
these two defines will make all calls using ANSI version yet assumes caller supply utf8 string with char* , so we should not return wchar*

**Comment by gulrak** [comment]
I'm not sure if I understand the issue correctly. Actually the C++17 standard is clear quite clear: _"For Windows-based operating systems, value_type is wchar_t and preferred_separator is the backslash character (L’\\’)."_ There is no dependency on the `UNICODE` or `_UNICODE` define, and the Microsoft documentation describes their `std::filesystem::path::value_type` as:
```cpp
#if _WIN32_C_LIB
typedef wchar_t value_type;
#else // assume POSIX
typedef char value_type;
#endif // filesystem model now defined
```
So only on non-Windows targets it is `char`, no dependency of `UNICODE` or `_UNICODE` either.

**Comment by gulrak** [comment]
Closing this, as implementation matches the standard and the official implementation of microsoft in this regard.
