### ISSUE TITLE
Termux has no <filesystem>; could this replace it?

### ISSUE THREAD

**Issue by xloem** [gulrak/filesystem#134]
On termux there is a c++ compiler but using std::filesystem makes linking errors: https://github.com/termux/termux-packages/issues/6275#issuecomment-899061044 [edit: I had pasted the wrong link, this now is the right one].

If the header files are removed, could this be a drop-in replacement?

Termux has a single github repository of all their .deb scripts somewhere; one could theoretically be made for this project.

**Comment by gulrak** [comment]
Sorry for the late reply, I had some very busy weeks at my job.

I'm quite confident one should be able to use this as a way to replace `std::filesystem` in that use-case, but only as far as you can control the used namespace for calling filesystem, so for your own code this should simply work. There are projects using it with pre-22 NDKs successfully. If something does not work as expected I sure try to help with usage or fixing found issues.

Still, I do not develop on Android myself and I'm not a termux user, so I don't see myself able to provide a specific script for it, and I would not release a version or wrapper myself that puts `ghc::filesystem` inside the `std` namespace.

**Comment by xloem** [comment]
I guess the question would boil down to whether there would any problems with clang's c++ library if this replaced their filesystem header.

It sounds like it's possible but not something you plan for nor support nor expect to be supporting on android.  Thank you.
