### ISSUE TITLE
GHC_NO_DIRENT_D_TYPE should be defined on Solaris

### ISSUE THREAD

**Issue by lukyhruska96** [gulrak/filesystem#142]
**Describe the bug**
Filesystem fails to compile (filesystem/filesystem.hpp) on Solaris because of missing d_type in dirent structure.

**Additional context**
[Doxygen issue](https://github.com/doxygen/doxygen/issues/9243)

**Comment by gulrak** [comment]
I'll look into it.

**Comment by phprus** [comment]
https://github.com/lukyhruska96/doxygen/commit/f751ce0d514def462798352827515126c45037a5

**Comment by gulrak** [comment]
I'll decided against another `GHC_NO_DIRENT_D_TYPE` and instead removed it and implemented compile time detection of the `dirent` variant. Got the whole test suite to successfully run on a Solaris 10 and hopefully will make a release until tomorrow.
Just need to figure out the GitHub workflow issue with VS2019.

**Comment by phprus** [comment]
@gulrak
CentOS 8 build is failed.
Solution: migrate from CentOS 8 to CentOS 8 Stream (like this https://github.com/gulrak/filesystem/pull/140/commits/e8a17c131952c86563ff0ba7e08896a4f2594216)

**Comment by gulrak** [comment]
Released with [v1.5.12](https://github.com/gulrak/filesystem/releases/tag/v1.5.12).
