### ISSUE TITLE
The CMake build definition doesn't contain a version

### ISSUE THREAD

**Issue by robbert-vdh** [gulrak/filesystem#148]
I recently replaced `Boost.Filesystem` with `ghc::filesystem` in [yabridge](https://github.com/robbert-vdh/yabridge). I'm using Meson, and during ordinary builds the `ghc_filesystem` dependency resolves to a subproject wrap dependency contained within the repo, but when packaging yabridge for distro repos they usually want to use their own repo dependencies instead of vendored ones. In theory that should work without any changes if the library ships a pkgconfig file or a CMake build definition (in `ghc::filesystem`'s case though I had to manually add `modules : 'ghcFilesystem::ghc_filesystem'` to the definition because it somehow doesn't export that by default like most other CMake dependencies do). The problem is that while this in theory works, the definitions in `/usr/lib/cmake/ghc_filesystem` don't contain any versions. So the following dependency will fail to resolve as the version bound cannot be satisfied:

```meson
ghc_filesystem_dep = dependency('ghc_filesystem', modules : 'ghcFilesystem::ghc_filesystem', version : '>=1.5.0')
```

Could you please consider adding a version number to the project? Using unversioned dependencies can otherwise result in all sorts of problems.

**Comment by gulrak** [comment]
Should be doable, Thanks for the report.
