### ISSUE TITLE
Missing include <vector> in forward declarations

### ISSUE THREAD

**Issue by Mooseart** [gulrak/filesystem#15]
Seems like std::vector is being used but not included. This is with forward declaration by including ghc/fs_std_fwd.hpp and happens only on Windows.

Check in ghc/filesystem.hpp:1009

Solved by adding #include <vector> just before #endif  // GHC_EXPAND_IMPL

**Comment by gulrak** [comment]
Indeed, that is missing. In their blog entry to C++17/20 features of VS2019 they saild they rearranged their own headers so they include less, so I guess the error was hidden by former "greediness" of MSVC headers.

**Comment by gulrak** [comment]
Fix with 61182d039f1ce9eb16a25e7111096e0c33c160e7 on master. Thank you for reporting.

**Comment by Mooseart** [comment]
This problem showed up for me when building with 2017 actually. Maybe the tests include vector on a higher level, or they don't use the forward declaration construct?
Either way, I tested with master now and it compiles fine with vs2017 so I think we can close it. Thanks!
