### ISSUE TITLE
Wrong result from stem/filename/extension when the ':' character is present in the filename

### ISSUE THREAD

**Issue by petersjogren** [gulrak/filesystem#156]
I suspect that this is a bug. std::filesystem behaves as expected but ghc::filesystem does not behave as expected (see below).

On Mac with ghc::filesystem:
A path with the filename "t:est.txt"

extension() returns "". Expected: ".txt"
filename() returns "t:". Expected: "t:est.txt"
stem() returns "t:". Expected: "t:est"

These tests all fail:
CHECK(fs::path("t:est.txt").extension() == ".txt");
CHECK(fs::path("t:est.txt").filename() == "t:est.txt");
CHECK(fs::path("t:est.txt").stem() == "t:est");

**Comment by gulrak** [comment]
Oh, that is unexpected, indeed. I'll look into it.

**Comment by gulrak** [comment]
Released with [v1.5.14](https://github.com/gulrak/filesystem/releases/tag/v1.5.14).
