### ISSUE TITLE
Warning when compiling with Microsoft compiler

### ISSUE THREAD

**Issue by albert-github** [gulrak/filesystem#157]
With the Microsoft compiler (Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64) we get the warning like:
```
warning C4191 'operator': unsafe conversion from 'type_of_expression' to 'type_required'
```
for:

https://github.com/gulrak/filesystem/blob/cd6805e94dd5d6346be1b75a54cdc27787319dd2/include/ghc/filesystem.hpp#L1959

and
https://github.com/gulrak/filesystem/blob/cd6805e94dd5d6346be1b75a54cdc27787319dd2/include/ghc/filesystem.hpp#L1983

**Comment by gulrak** [comment]
Released with [v1.5.14](https://github.com/gulrak/filesystem/releases/tag/v1.5.14).
