### ISSUE TITLE
Warning when compiling with Microsoft compiler

### ISSUE THREAD

**Issue by albert-github** [gulrak/filesystem#158]
With the Microsoft compiler (Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64) we get the warning like:
```
warning C4127 conditional expression is constant
```

for:
https://github.com/gulrak/filesystem/blob/cd6805e94dd5d6346be1b75a54cdc27787319dd2/include/ghc/filesystem.hpp#L2278

**Comment by GXTX** [comment]
Dupe of #147

**Comment by albert-github** [comment]
Closing as duplicate of #147
