### ISSUE TITLE
GHC_NO_DIRENT_D_TYPE should be defined on Haiku

### ISSUE THREAD

**Issue by Begasus** [gulrak/filesystem#159]
**Describe the bug**
 Filesystem fails to compile (filesystem/filesystem.hpp) on Haiku because of missing d_type in dirent structure.

**Additional context**
https://github.com/doxygen/doxygen/pull/9610

**Comment by gulrak** [comment]
This is a valid solution for the used version ghc::filesystem v1.5.6, but with #142 this is not needed any more, as starting with v1.5.12 the code detects the presence of `dirent.d_type` automatically at compile time.

**Comment by Begasus** [comment]
Could still use the detection for Haiku, otherwise I'm getting: error "Operating system currently not supported!":

From: https://github.com/gulrak/filesystem/blob/master/include/ghc/filesystem.hpp#L79

```diff
#elif defined(__QNX__)
#define GHC_OS_QNX
+#elif defined(__HAIKU__)
+#define GHC_OS_HAIKU
#else
```

**Comment by Begasus** [comment]
Related PR: https://github.com/gulrak/filesystem/pull/163

**Comment by Begasus** [comment]
This can be closed I think, created a stand-alone package on Haiku with the related PR here, build and install seem OK.
I'm doing a build for catch2 to see if I can run the provided tests here also, thanks so far! :)

**Comment by gulrak** [comment]
You are right, I will add the detection.

**Comment by Begasus** [comment]
Upstream PR merged, thanks! 👍
