### ISSUE TITLE
Clean build on Visual Studio 2019

### ISSUE THREAD

**Issue by Mooseart** [gulrak/filesystem#16]
I know your tests are currently not being run on 2019. I gave it a shot and tried to compile anyways. I got a bunch of warnings and an error in one of the examples. Error was easy enough to fix (missing include) but the warnings are mostly about template magic in some system header. I don't get it exactly but seems to be originating from the utf8 conversion somehow.
..so VS2019 build would be awesome to have. Thanks for sharing this great lib.

**Comment by gulrak** [comment]
Thank you for testing. Currently I don't have access to a system with an installed VC2019, so I couldn't check. I'll try to set up a VM with it, and look into it.

**Comment by gulrak** [comment]
I revamped the char size dispatching, everything builds warning free and tests are running now on a VS2019 in my VM. Everything should be fine, but I will wait a few days before making a release, if something else comes up.

**Comment by Mooseart** [comment]
Ah, nice! I've tested with your latest fix and it totally solves it on my side too. Thanks a lot for looking into it. I think you can close it then, unless you have any more work planned with respect to this.

**Comment by gulrak** [comment]
Thanks for rechecking!
