### ISSUE TITLE
GHC_FILESYSTEM_WITH_INSTALL always on

### ISSUE THREAD

**Issue by DioEgizio** [gulrak/filesystem#160]
https://github.com/gulrak/filesystem#git-submodule-and-cmake says it should be off when used as a submodule, but it's actually always on :p

https://github.com/gulrak/filesystem/blob/cd6805e94dd5d6346be1b75a54cdc27787319dd2/CMakeLists.txt#L18

**Comment by gulrak** [comment]
I'll look into it.

**Comment by gulrak** [comment]
Released with [v1.5.14](https://github.com/gulrak/filesystem/releases/tag/v1.5.14).
