### ISSUE TITLE
Planning for a new release

### ISSUE THREAD

**Issue by albert-github** [gulrak/filesystem#164]
The current release is 1.5.12 from April 3, 2022 are there any plans for a new release?

**Comment by gulrak** [comment]
Yes, I hope to make one this month or first week of April. Started to look into tickets and PRs for it a few days ago again. Sorry for the delay, had more workload last year and had to prioritize the little free time for more recreational coding, but things look better now.

**Comment by gulrak** [comment]
Was done just now. :wink:
