### ISSUE TITLE
macOS 10.12 cmake build fail

### ISSUE THREAD

**Issue by wang-zuxian** [gulrak/filesystem#168]
On macOS 10.12, build with this cmd : cmake -S . -B build;cmake --build build, then it show error like this:
[  4%] Building CXX object test/CMakeFiles/filesystem_test.dir/filesystem_test.cpp.o
In file included from /Users/test/Desktop/filesystem-1.5.14/test/filesystem_test.cpp:62:
/Users/test/Desktop/filesystem-1.5.14/include/ghc/filesystem.hpp:4681:11: error: 
      no member named 'utimensat' in the global namespace
    if (::utimensat((int)AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW...
        ~~^
1 error generated.
make[2]: *** [test/CMakeFiles/filesystem_test.dir/filesystem_test.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/filesystem_test.dir/all] Error 2
make: *** [all] Error 2

ghc::filesystem version is 1.5.14.
The macro __MAC_10_13 is not defined at macOS 10.12. I replace __MAC_10_13 with 101300, and it works.

Thanks gulrak.

**Comment by wang-zuxian** [comment]
ghc::filesystem version is 1.5.14

**Comment by gulrak** [comment]
Hi!
Thank you, for reporting this. Did you try the current master?
By coincidence there was PR #167 merged over the weekend that might help with that.
Let me know if that fixes it for you, as I don't have a 10.12 platform available.
Best wishes,
gulrak

**Comment by wang-zuxian** [comment]
Sorry,I forgot to check master. It  work now on macOS 10.12.
Thanks very much!
