### ISSUE TITLE
Missing options parameter in copy

### ISSUE THREAD

**Issue by Jineapple** [gulrak/filesystem#22]
In line 3027 of filesystem.hpp, if the copy()-method resolves to a copy_file with two file paths given, the options parameter is not passed on. 
`                copy_file(from, to, ec);`
This causes issues e.g. if the target file already exists and overwrite_existing or update_existing was passed as an option.

**Comment by gulrak** [comment]
Thanks for finding it! I will push a fix to master today, and scheduled a release for the weekend.

**Comment by gulrak** [comment]
Fix released with v1.2.4
