### ISSUE TITLE
toUtf8 template argument from 'const Source'

### ISSUE THREAD

**Issue by Jineapple** [gulrak/filesystem#26]
Here's the errors I get when compiling a project with filesystem as a submodule:

D:\jonas\Code\WololoKingdoms\libwololokingdoms\third_party\filesystem\include\ghc\filesystem.hpp:1455: 
Error: C2672: 'ghc::filesystem::detail::toUtf8': no matching overloaded function found
Error: C2784: 'std::string ghc::filesystem::detail::toUtf8(const charT *)': could not deduce template argument for 'const charT *' from 'const Source'
Error: C2784: 'std::string ghc::filesystem::detail::toUtf8(const std::basic_string<_Elem,_Traits,_Alloc> &)': could not deduce template argument for 'const std::basic_string<_Elem,_Traits,_Alloc> &' from 'const Source'

This error has occasionally appeared and disappeared before, so it's quite possible that it's a problem on my end, but this time I can't seem to make it go away with updating/cleaning as was the case before. I'm not sure how to handle this, so any tips/pointers would be appreciated if someone has an idea what the issue might be.

**Comment by gulrak** [comment]
I need a little bit more information. It looks like there is a creation of an fs::path involved.
First: What operating system, compiler, compiler version, C++ languange version (C++11/14/17) are you experiencing this error with?
Are there more lines of the message? I would need to know the type used, to construct the path (either explicitly or implicitly), or a small sample-code, so in what situation is ghc::fs called when the error occurs.
With more information I will try fixing/helping. But it will be later today when I'm back in my spare time.

**Comment by Jineapple** [comment]
Sorry about that - OS is Windows 10, Build 1903. C++17 with MSVC 2017 Version 14.16.27023
```
D:\jonas\Code\WololoKingdoms\libwololokingdoms\third_party\filesystem\include\ghc\filesystem.hpp:1455:
Error: C2672: 'ghc::filesystem::detail::toUtf8': no matching overloaded function found
D:\jonas\Code\WololoKingdoms\libwololokingdoms\third_party\filesystem\include\ghc\filesystem.hpp:2409: see reference to function template instantiation 'ghc::filesystem::path::path<std::basic_string_view<char,std::char_traits<char>>,ghc::filesystem::path>(const Source &,ghc::filesystem::path::format)' being compiled
Error: C2784: 'std::string ghc::filesystem::detail::toUtf8(const charT *)': could not deduce template argument for 'const charT *' from 'const Source'
Error: C2784: 'std::string ghc::filesystem::detail::toUtf8(const std::basic_string<_Elem,_Traits,_Alloc> &)': could not deduce template argument for 'const std::basic_string<_Elem,_Traits,_Alloc> &' from 'const Source'
```
It's called from the compare function, but I'm having a hard time figuring out where that is used or with what type. If that's not enough info for you to have an idea where the problem might be it's fine, I'll spend some more time digging myself - just thought I'd ask if you happened to have this error before.

**Comment by Jineapple** [comment]
Updating the submodule to the newest commit seems to have fixed the issue. This seems to happen if the submodule commit used is out of date compared to the remote, not sure why. In any case, it is fixed for now. I'll have to see if it happens again, but it would be a problem on my end, thanks for your time anyway.

**Comment by gulrak** [comment]
No problem, you are welcome.
