### ISSUE TITLE
Fix conversion warnings

### ISSUE THREAD

**Issue by chfast** [gulrak/filesystem#29]
**Is your feature request related to a problem? Please describe.**

This is a header-only library therefore it is usually built with the warning level of the project which includes it. With some additional warnings enabled the `filesystem.hpp` does not compile cleanly.

**Describe the solution you'd like**

Build the project with `-Wconversion -Wsign-conversion -Wpedantic` and fix the reported warnings.

**Comment by gulrak** [comment]
That shouldn't be a problem. I will not make it during the week, but I try to get to it during the weekend.

**Comment by chfast** [comment]
Ok, no rush. I have a workaround in place (`-isystem`).

**Comment by gulrak** [comment]
Released with v1.2.6
