### ISSUE TITLE
Undeclared identifier DWORD

### ISSUE THREAD

**Issue by Mooseart** [gulrak/filesystem#39]
Hi.
Believe I've found a bug:
Error C2065 'DWORD': undeclared identifier ghc\filesystem.hpp(1089)

Noticed this now (on Windows, vs2019) when upgrading from an older release of your repo.

So I get this when using the forward declarations. Apparently it now relies on having DWORD already defined which wasn't the case before. My application does not include windows.h, hence there's no DWORD.

I see a few options:
* Change the declaration of make_system_error() to not use DWORD.
* Include windows.h always, not only for implementation.
* typedef unsigned long DWORD if not already defined.

Not sure what works best here but the latter two are probably best to avoid if possible.

**Comment by gulrak** [comment]
Thanks for the report! I'll look into it, was a few days and got back with an annoying cold.

**Comment by gulrak** [comment]
Fix released with v1.2.10
