### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by dtarakanov1** [gulrak/filesystem#47]
**Is your feature request related to a problem? Please describe.**
The BSD-3-Clause license type complicates the `filesystem` library usage.

**Describe the solution you'd like**
The MIT license is more permissive, so it would be nice to apply it instead.

**Describe alternatives you've considered**
Any other permissive licenses are welcome.

**Additional context**
Our team is going to open source some library (under MIT license) and having a dependency on the BSD license is not okay then. So if the license type is not changed, we'll have to find another filesystem implementation.

**Comment by gulrak** [comment]
I'm sorry to hear, that the chosen license is not the one fitting your needs. I selected BSD-3 because of the no-endorsement-clause and I can not see how the MIT license will give me the same effect.

Besides that, there is the legal need of all contributors to agree to a license change, and that might be difficult to obtain.

**Comment by dtarakanov1** [comment]
Forgot to mention.
The rule is very simple: a BSD-3-Clause licensed library cannot be used in MIT licensed products (BSD-2-Clause can).
Since MIT is quite commonly used, so I suspect many of the `ghc.filesystem` library users violate the license.
Fortunately there is `boost.filesystem` as well, though it has some downsides.

**Comment by gulrak** [comment]
It's not that I'm totally against a re-licensing to MIT, but there still is the need of every other contributor to agree to the change to MIT license, so we can give it a try:

To all [contributors](https://github.com/gulrak/filesystem/graphs/contributors):

If you agree with to a re-licenseing from [BSD-3-Clause](https://github.com/gulrak/filesystem/blob/master/LICENSE) to the [MIT](https://opensource.org/licenses/MIT) license, please reply with a :+1:

**Comment by asmaloney** [comment]
👍

**Comment by cybik** [comment]
I hereby 👍 this.

**Comment by jwnimmer-tri** [comment]
Yes, I agree :+1: to MIT relicensing.

**Comment by karjonas** [comment]
I agree as well.  +1

**Comment by Zer0xFF** [comment]
You have my blessings

**Comment by kleuter** [comment]
👍

**Comment by actboy168** [comment]
👍

**Comment by fenglc** [comment]
I agree as well.

**Comment by jeanguyomarch** [comment]
Yes, I agree :+1: to MIT relicensing.

**Comment by tohammer** [comment]
I agree to MIT relicensing :+1:

**Comment by gulrak** [comment]
Great, all agreed! - Thank you so much for participating!

So I plan a release of v1.3.0 with under MIT license around the upcomming weekend.
Thanks for bringing this up @dtarakanov1!

**Comment by asmaloney** [comment]
@gulrak - thank _you_ for all your work on this library!

**Comment by gulrak** [comment]
New release v1.3.0 just published under MIT license!
