### ISSUE TITLE
Small append differences on Windows, compared with boost

### ISSUE THREAD

**Issue by greenkalx** [gulrak/filesystem#64]
Our unit tests all harness boost::filesystem::path, which has some differences from std::filesystem::path and ghc::filesystem::path.
Are these strictly defined in the standard?

ex1/
```
p1 = "c:/bbb"
p2 = "";
p3 = p1 / p2;   == "c:/bbb/"    (with ghc)
p3 = p1 / p2;   == "c:/bbb"     (with boost)
```

ex2/
```
p1 = "c:/bbb"
p2 = "/ccc";
p3 = p1 / p2;   == "c:/ccc"       (with ghc)
p3 = p1 / p2;   == "c:/bbb/ccc"   (with boost)
```

If I want the same behaviour, can you recommend how?

I considered making path::append virtual, to:
ex1/ skip appending if the rhs is empty
ex2/ strip the leading or trailing separator on entry

Or add a ghc::filesystem::path member to my path class, instead of inheriting. But this requires forwarders for every path function.

**Comment by gulrak** [comment]
These are changes that where introduced to the standard between `std::experimental::filesystem` and `std::filesystem`.

For ex1: The standard shows the append example:
```
path("foo") / ""; // yields "foo/"
```

For ex2: The standard explicitly defines: _"If `p.has_root_directory()`, then removes any root directory and relative path from the generic format pathname. "_ and they show an example:
```
path("c:foo") / "/bar"; // yields "c:/bar"
```
This one sure is the most controversial change in the standard, but it was deliberately chosen. It makes append behave like `cd` shell command in that it replaces the current directory or parts of it with the argument if it is absolute or starts with a separator. Some find this the natural way, but sure some disagree.

I know boost does it differently, but this library is build to be a `std::filesystem`-behavior implementation. I tried my best to follow the standard behavior and did lot's of testing with other implementations of `std::filesystem` so I would not break conformance to go back to boost.

I would like to not introduce virtual functions into `path` as those come with a price and it's not the standard api.

Btw: There sure are various behavior differences in `std::filesystem` implementations over the compilers: https://gulrak.net/posts/2019-std-filesystem-corner-cases/

**Comment by greenkalx** [comment]
Thanks for the clarification on a standard that looks very non-standard between compilers, STL versions, platforms, and boost.
I'm going to maintain the majority of our tests for now.
With the time I spent on this and other STL oddities, I would have been further ahead by building my own classes on C. (String, Path, FileSystem..)
