### ISSUE TITLE
[Question] iOS support

### ISSUE THREAD

**Issue by dolphineye** [gulrak/filesystem#67]
Hi,

We are currently checking for alternatives to boost filesystem.
As of now, unless mistaken, std::filesystem is still not supported on iOS < 13, and after searching a bit, I stumbled on your project's page.

I did not see any mention of iOS in the supported platforms. Is this just a lack of time to test on iOS, or would this require extra work for this platform?

Thanks!

**Comment by gulrak** [comment]
Actually I never tried, even if I actually use iOS devices and sometimes develop for them. It might be a challenge to get some automated CI testing going for it, if possible at all, but I would suggest to give it a try, and if something is not working but should, besides the sandboxing limits of iOS that is, I'll try to look into it.

**Comment by dolphineye** [comment]
Thanks, I will look into it and keep you posted if I face issues. I don't have any ETA for the testing though, so I'll keep you posted.

**Comment by dolphineye** [comment]
Hey,

So far it seems everything works fine on iOS for us.

Thanks for everything 👍
