### ISSUE TITLE
C++20 support?

### ISSUE THREAD

**Issue by shrinktofit** [gulrak/filesystem#71]
As you know, MacOS support `-std=c++20` even in `10.14` but does not support `<filesystem>` until `10.15`.

`char8_t`, `std::u8string` are coming soon. `std::filesystem::path::string()` will returns `std::u8string` instead of `std::string`.

**Comment by gulrak** [comment]
Indeed, C++20 support is on my list of planned features, I just didn't find time to really work on it. I guess it will take me a few more weeks to finish it, as it is not needed in my payed work project and my free time available for it is limited. It will be released in v1.4.0.

**Comment by gulrak** [comment]
This is now solved with release [v1.4.0](https://github.com/gulrak/filesystem/releases/tag/v1.4.0)

**Comment by shrinktofit** [comment]
> This is now solved with release [v1.4.0](https://github.com/gulrak/filesystem/releases/tag/v1.4.0)

Thank you!
