### ISSUE TITLE
About MSVC and __cplusplus

### ISSUE THREAD

**Issue by unterumarmung** [gulrak/filesystem#76]
In MSVC there's special macro called `_MSVC_LANG` that works fine without `/Zc:cplusplus` flag
So you can build your own macro, for example:
https://github.com/oneapi-src/oneTBB/blob/8632c278467f99941caff8a666fa33e57650c53f/include/tbb/detail/_config.h#L39-L47

**Comment by gulrak** [comment]
Released with v1.3.8
