### ISSUE TITLE
Expected constexpr on detail::EnableBitmask<Enum> operator...(Enum X, Enum Y)

### ISSUE THREAD

**Issue by phprus** [gulrak/filesystem#79]
**Describe the bug**
C++11 17.5.2.1.3 Bitmask types:
constexpr bitmask operator&(bitmask X, bitmask Y)
constexpr bitmask operator|(bitmask X, bitmask Y)
constexpr bitmask operator^(bitmask X, bitmask Y)
constexpr bitmask operator~(bitmask X)

**To Reproduce**
Using the perm_options operator... in a constexpr function results in a compilation error.

**Expected behavior**
Compiling without error.

**Comment by gulrak** [comment]
Seems I missed that, thanks for reporting, will look into it. Just a few minutes too late for v1.3.8.

**Comment by gulrak** [comment]
I'll have to look into it, don't have a locale installation of VS2013, so appveyor needs to be my verification, as long as they support it.

**Comment by gulrak** [comment]
This is now part of release [v1.3.10](https://github.com/gulrak/filesystem/releases/tag/v1.3.10)
