### ISSUE TITLE
vs2013 update5 support

### ISSUE THREAD

**Issue by ppjxhyyy** [gulrak/filesystem#80]
as the title

**Comment by gulrak** [comment]
As I don't have a local installation ov VS2013 available, I would need to rely on Appveyor for that. I'll look into it.

**Comment by ppjxhyyy** [comment]
> As I don't have a local installation ov VS2013 available, I would need to rely on Appveyor for that. I'll look into it.

I think this is very useful, after all c++17 already has a filesystem, it would be a waste to just use it as a backup!

**Comment by gulrak** [comment]
Uh... the first test compile looks [quite bad](https://ci.appveyor.com/project/gulrak/filesystem/builds/36350921/job/2sm02jnjn809kmh6)...

I understand, that it might be useful to have, but a major requirement of `ghc::filesystem` is a C++11 capable compiler. From the looks on the errors of that compile, there seem to be a lot of issues with C++11 features still open in VC2013 Update 5. The documented [C++11 support table](https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)?redirectedfrom=MSDN) shows quite a list of non-implemented features too.

It looks like it would take quite an effort to work around those quirks and not break support for any of the many compilers currently working. An effort that would need time and I would need a local installation, as fixing lots of issues with remote compilation on appveyor only is a difficult task.

I might take another look into it over the next weekend, but my first impression is, that it is out of reach for the time I can invest and I do not plan to generally switch to support C++98/03 in the future, C++11 should stay the minimum requirement. If I find some simple workarounds, maybe, but it doesn't look too promising, I'm sorry.

**Comment by ppjxhyyy** [comment]
ok, fine. Maybe I should have chosen booster::filesystem or implemented one myself.

> Uh... the first test compile looks [quite bad](https://ci.appveyor.com/project/gulrak/filesystem/builds/36350921/job/2sm02jnjn809kmh6)...
> 
> I understand, that it might be useful to have, but a major requirement of `ghc::filesystem` is a C++11 capable compiler. From the looks on the errors of that compile, there seem to be a lot of issues with C++11 features still open in VC2013 Update 5. The documented [C++11 support table](https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)?redirectedfrom=MSDN) shows quite a list of non-implemented features too. It was already quite some work to support VS2015, but I sure wanted to support it, as a pre-C++17 IDE.
> 
> It looks like it would take quite an effort to work around those quirks and not break support for any of the many compilers currently working. An effort that would need time and I would need a local installation, as fixing lots of issues with remote compilation on appveyor only is a difficult task.
> 
> I might take another look into it over the next weekend, but my first impression is, that it is out of reach for the time I can invest and I do not plan to generally switch to support C++98/03 in the future, C++11 should stay the minimum requirement. If I find some simple workarounds, maybe, but it doesn't look too promising, I'm sorry.

**Comment by gulrak** [comment]
As I expected, it is more work than I can put into it, so without a non breaking PR that doesn't clutter the source too much, VS2013 will stay unsupported. I'm sorry.
