### ISSUE TITLE
There is no utimensat function on centos5

### ISSUE THREAD

**Issue by ugenehan** [gulrak/filesystem#82]
There is no utimensat function on centos5 .

**Comment by gulrak** [comment]
As far as I know, the default compiler for CentOS5 is some GCC 4.x and CentOS5 has reached EOL March 2017, and even CentOS6 reached EOL just last month. `ghc::filesystem` is tested on CentOS7 and up and I have no system to test such old releases on, so I sadly have to say I'm not able to support it myself. I guess I would accept non breaking PRs that don't clutter the code too much, but I'm not able to do it myself, I'm sorry.
