### ISSUE TITLE
It would be great to offer this in vcpkg....

### ISSUE THREAD

**Issue by cmaughan** [gulrak/filesystem#87]
Would need a portfile submitting.

**Comment by gulrak** [comment]
I'm open for PRs, but I'm not using vcpkg, so me doing it sure will take a while, as I need to find time to setup an environment to test this.

**Comment by gulrak** [comment]
There is now a port in [vcpkg](https://github.com/microsoft/vcpkg) with [this PR](https://github.com/microsoft/vcpkg/pull/16936)
It was not my work, so really want to thank @luncliff for that work!
