### ISSUE TITLE
Invalid warning option on MSVC

### ISSUE THREAD

**Issue by phprus** [gulrak/filesystem#95]
File: https://github.com/gulrak/filesystem/blob/master/cmake/GhcHelper.cmake#L53

Invalid option: ``/wd"4996"`` (error: ``cl : Command line error D8021 : invalid numeric argument '/wd"4996"'``)

Correct option: ``/wd4996`` (MSDN: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-160)

**Comment by gulrak** [comment]
Strangely I got no error with both syntaxes on my VS2019 installation or on AppVeyor with 2015/2017/2019 runs, but I changed it anyway. Thanks for reporting it.

**Comment by gulrak** [comment]
This is now part of release [v1.5.2](https://github.com/gulrak/filesystem/releases/tag/v1.5.2)
